[package]
name = "newlib_redox"
version = "0.1.0"

[lib]
name = "newlib_redox"
crate-type = ["staticlib"]

[profile.release]
lto = true

[dependencies]
redox_syscall = "0.1"
byteorder = { version = "1", default-features = false }
libc = { version = "0.2", default-features = false }
